# Config file for recompiling Animal Forest (Doubutsu no Mori) N64.

[input]
elf_path = "/data/data/com.termux/files/home/AnimalForest64/animalforest.elf"
output_func_path = "output_code/functions"
single_file_output = false
use_absolute_symbols = false

output_binary_path = "output_code/animalforest.bin"
unpaired_lo16_warnings = false
allow_exports = true
strict_patch_mode = false

[options]
rom_path = "/data/data/com.termux/files/home/AnimalForest64/baserom.z64"
