.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
nonmatching func_80000400, 0x34

glabel func_80000400
    /* 1000 80000400 3C088004 */  lui        $t0, %hi(D_8003E940)
    /* 1004 80000404 2508E940 */  addiu      $t0, $t0, %lo(D_8003E940)
    /* 1008 80000408 24095D50 */  addiu      $t1, $zero, 0x5D50
  .L8000040C:
    /* 100C 8000040C 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1010 80000410 AD000000 */  sw         $zero, 0x0($t0)
    /* 1014 80000414 AD000004 */  sw         $zero, 0x4($t0)
    /* 1018 80000418 1520FFFC */  bnez       $t1, .L8000040C
    /* 101C 8000041C 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
    /* 1020 80000420 3C0A8002 */  lui        $t2, %hi(D_80025CC0)
    /* 1024 80000424 3C1D8004 */  lui        $sp, %hi(D_8003F330)
    /* 1028 80000428 254A5CC0 */  addiu      $t2, $t2, %lo(D_80025CC0)
    /* 102C 8000042C 01400008 */  jr         $t2
    /* 1030 80000430 27BDF330 */   addiu     $sp, $sp, %lo(D_8003F330)
endlabel func_80000400
    /* 1034 80000434 00000000 */  nop
    /* 1038 80000438 00000000 */  nop
    /* 103C 8000043C 00000000 */  nop
    /* 1040 80000440 00000000 */  nop
    /* 1044 80000444 00000000 */  nop
    /* 1048 80000448 00000000 */  nop
    /* 104C 8000044C 00000000 */  nop
    /* 1050 80000450 00000000 */  nop
    /* 1054 80000454 00000000 */  nop
    /* 1058 80000458 00000000 */  nop
    /* 105C 8000045C 00000000 */  nop
