.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_80000A40, 0x4C

glabel func_80000A40
    /* 1640 80000A40 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1644 80000A44 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1648 80000A48 AFA40018 */  sw         $a0, 0x18($sp)
    /* 164C 80000A4C 0C027067 */  jal        func_8009C19C
    /* 1650 80000A50 00000000 */   nop
    /* 1654 80000A54 10400005 */  beqz       $v0, .L80000A6C
    /* 1658 80000A58 8FA40018 */   lw        $a0, 0x18($sp)
    /* 165C 80000A5C 0C026FFA */  jal        func_8009BFE8
    /* 1660 80000A60 00000000 */   nop
    /* 1664 80000A64 10000004 */  b          .L80000A78
    /* 1668 80000A68 00401825 */   or        $v1, $v0, $zero
  .L80000A6C:
    /* 166C 80000A6C 0C00B1F2 */  jal        func_8002C7C8
    /* 1670 80000A70 00000000 */   nop
    /* 1674 80000A74 00401825 */  or         $v1, $v0, $zero
  .L80000A78:
    /* 1678 80000A78 00601025 */  or         $v0, $v1, $zero
    /* 167C 80000A7C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1680 80000A80 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 1684 80000A84 03E00008 */  jr         $ra
    /* 1688 80000A88 00000000 */   nop
endlabel func_80000A40

nonmatching func_80000A8C, 0x44

glabel func_80000A8C
    /* 168C 80000A8C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1690 80000A90 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1694 80000A94 AFA40018 */  sw         $a0, 0x18($sp)
    /* 1698 80000A98 0C027067 */  jal        func_8009C19C
    /* 169C 80000A9C 00000000 */   nop
    /* 16A0 80000AA0 10400005 */  beqz       $v0, .L80000AB8
    /* 16A4 80000AA4 8FA40018 */   lw        $a0, 0x18($sp)
    /* 16A8 80000AA8 0C027010 */  jal        func_8009C040
    /* 16AC 80000AAC 00000000 */   nop
    /* 16B0 80000AB0 10000004 */  b          .L80000AC4
    /* 16B4 80000AB4 8FBF0014 */   lw        $ra, 0x14($sp)
  .L80000AB8:
    /* 16B8 80000AB8 0C00B208 */  jal        func_8002C820
    /* 16BC 80000ABC 00000000 */   nop
    /* 16C0 80000AC0 8FBF0014 */  lw         $ra, 0x14($sp)
  .L80000AC4:
    /* 16C4 80000AC4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 16C8 80000AC8 03E00008 */  jr         $ra
    /* 16CC 80000ACC 00000000 */   nop
endlabel func_80000A8C

nonmatching func_80000AD0, 0xF0

glabel func_80000AD0
    /* 16D0 80000AD0 27BDFF68 */  addiu      $sp, $sp, -0x98
    /* 16D4 80000AD4 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 16D8 80000AD8 AFB00028 */  sw         $s0, 0x28($sp)
    /* 16DC 80000ADC AFA40098 */  sw         $a0, 0x98($sp)
    /* 16E0 80000AE0 AFA5009C */  sw         $a1, 0x9C($sp)
    /* 16E4 80000AE4 AFA600A0 */  sw         $a2, 0xA0($sp)
    /* 16E8 80000AE8 AFA700A4 */  sw         $a3, 0xA4($sp)
    /* 16EC 80000AEC 8FA40098 */  lw         $a0, 0x98($sp)
    /* 16F0 80000AF0 27A50094 */  addiu      $a1, $sp, 0x94
    /* 16F4 80000AF4 27A60090 */  addiu      $a2, $sp, 0x90
    /* 16F8 80000AF8 0C009B13 */  jal        func_80026C4C
    /* 16FC 80000AFC 27A7008C */   addiu     $a3, $sp, 0x8C
    /* 1700 80000B00 8FAE008C */  lw         $t6, 0x8C($sp)
    /* 1704 80000B04 8FAF0090 */  lw         $t7, 0x90($sp)
    /* 1708 80000B08 8FA400AC */  lw         $a0, 0xAC($sp)
    /* 170C 80000B0C 8FB800B0 */  lw         $t8, 0xB0($sp)
    /* 1710 80000B10 01CF1823 */  subu       $v1, $t6, $t7
    /* 1714 80000B14 10800004 */  beqz       $a0, .L80000B28
    /* 1718 80000B18 AFA30088 */   sw        $v1, 0x88($sp)
    /* 171C 80000B1C 0303082B */  sltu       $at, $t8, $v1
    /* 1720 80000B20 10200005 */  beqz       $at, .L80000B38
    /* 1724 80000B24 00808025 */   or        $s0, $a0, $zero
  .L80000B28:
    /* 1728 80000B28 0C009890 */  jal        func_80026240
    /* 172C 80000B2C 8FA40088 */   lw        $a0, 0x88($sp)
    /* 1730 80000B30 10000001 */  b          .L80000B38
    /* 1734 80000B34 00408025 */   or        $s0, $v0, $zero
  .L80000B38:
    /* 1738 80000B38 16000009 */  bnez       $s0, .L80000B60
    /* 173C 80000B3C 27A40034 */   addiu     $a0, $sp, 0x34
    /* 1740 80000B40 3C058004 */  lui        $a1, %hi(D_8003D1B0)
    /* 1744 80000B44 24A5D1B0 */  addiu      $a1, $a1, %lo(D_8003D1B0)
    /* 1748 80000B48 0C00B631 */  jal        func_8002D8C4
    /* 174C 80000B4C 8FA60088 */   lw        $a2, 0x88($sp)
    /* 1750 80000B50 3C048004 */  lui        $a0, %hi(D_8003D1B4)
    /* 1754 80000B54 2484D1B4 */  addiu      $a0, $a0, %lo(D_8003D1B4)
    /* 1758 80000B58 0C00A6AD */  jal        func_80029AB4
    /* 175C 80000B5C 27A50034 */   addiu     $a1, $sp, 0x34
  .L80000B60:
    /* 1760 80000B60 8FB900A0 */  lw         $t9, 0xA0($sp)
    /* 1764 80000B64 8FA800A4 */  lw         $t0, 0xA4($sp)
    /* 1768 80000B68 8FA900A8 */  lw         $t1, 0xA8($sp)
    /* 176C 80000B6C 8FA40098 */  lw         $a0, 0x98($sp)
    /* 1770 80000B70 8FA50094 */  lw         $a1, 0x94($sp)
    /* 1774 80000B74 8FA60090 */  lw         $a2, 0x90($sp)
    /* 1778 80000B78 8FA7008C */  lw         $a3, 0x8C($sp)
    /* 177C 80000B7C AFB0001C */  sw         $s0, 0x1C($sp)
    /* 1780 80000B80 AFB90010 */  sw         $t9, 0x10($sp)
    /* 1784 80000B84 AFA80014 */  sw         $t0, 0x14($sp)
    /* 1788 80000B88 0C00AE44 */  jal        func_8002B910
    /* 178C 80000B8C AFA90018 */   sw        $t1, 0x18($sp)
    /* 1790 80000B90 8FAA00B0 */  lw         $t2, 0xB0($sp)
    /* 1794 80000B94 8FAB0088 */  lw         $t3, 0x88($sp)
    /* 1798 80000B98 014B082B */  sltu       $at, $t2, $t3
    /* 179C 80000B9C 50200004 */  beql       $at, $zero, .L80000BB0
    /* 17A0 80000BA0 8FBF002C */   lw        $ra, 0x2C($sp)
    /* 17A4 80000BA4 0C0098A3 */  jal        func_8002628C
    /* 17A8 80000BA8 02002025 */   or        $a0, $s0, $zero
    /* 17AC 80000BAC 8FBF002C */  lw         $ra, 0x2C($sp)
  .L80000BB0:
    /* 17B0 80000BB0 8FB00028 */  lw         $s0, 0x28($sp)
    /* 17B4 80000BB4 27BD0098 */  addiu      $sp, $sp, 0x98
    /* 17B8 80000BB8 03E00008 */  jr         $ra
    /* 17BC 80000BBC 00000000 */   nop
endlabel func_80000AD0

nonmatching func_80000BC0, 0x2C

glabel func_80000BC0
    /* 17C0 80000BC0 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 17C4 80000BC4 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 17C8 80000BC8 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 17CC 80000BCC AFA00014 */  sw         $zero, 0x14($sp)
    /* 17D0 80000BD0 AFA00018 */  sw         $zero, 0x18($sp)
    /* 17D4 80000BD4 0C0098B4 */  jal        func_800262D0
    /* 17D8 80000BD8 AFAE0010 */   sw        $t6, 0x10($sp)
    /* 17DC 80000BDC 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 17E0 80000BE0 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 17E4 80000BE4 03E00008 */  jr         $ra
    /* 17E8 80000BE8 00000000 */   nop
endlabel func_80000BC0
    /* 17EC 80000BEC 00000000 */  nop
