.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_80000BF0, 0x110

glabel func_80000BF0
    /* 17F0 80000BF0 27BDFF28 */  addiu      $sp, $sp, -0xD8
    /* 17F4 80000BF4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 17F8 80000BF8 AFA400D8 */  sw         $a0, 0xD8($sp)
    /* 17FC 80000BFC AFA500DC */  sw         $a1, 0xDC($sp)
    /* 1800 80000C00 AFA600E0 */  sw         $a2, 0xE0($sp)
    /* 1804 80000C04 8FAE00D8 */  lw         $t6, 0xD8($sp)
    /* 1808 80000C08 8FA800D8 */  lw         $t0, 0xD8($sp)
    /* 180C 80000C0C 27A4007C */  addiu      $a0, $sp, 0x7C
    /* 1810 80000C10 8DCF0000 */  lw         $t7, 0x0($t6)
    /* 1814 80000C14 3C058004 */  lui        $a1, %hi(D_8003D1D8)
    /* 1818 80000C18 8FA900D8 */  lw         $t1, 0xD8($sp)
    /* 181C 80000C1C AFAF00D4 */  sw         $t7, 0xD4($sp)
    /* 1820 80000C20 8DD80004 */  lw         $t8, 0x4($t6)
    /* 1824 80000C24 AFB800D0 */  sw         $t8, 0xD0($sp)
    /* 1828 80000C28 8DD90008 */  lw         $t9, 0x8($t6)
    /* 182C 80000C2C AFB900CC */  sw         $t9, 0xCC($sp)
    /* 1830 80000C30 8D06000C */  lw         $a2, 0xC($t0)
    /* 1834 80000C34 10C00005 */  beqz       $a2, .L80000C4C
    /* 1838 80000C38 24A5D1D8 */   addiu     $a1, $a1, %lo(D_8003D1D8)
    /* 183C 80000C3C 0C00B631 */  jal        func_8002D8C4
    /* 1840 80000C40 8D270010 */   lw        $a3, 0x10($t1)
    /* 1844 80000C44 10000017 */  b          .L80000CA4
    /* 1848 80000C48 8FAB00DC */   lw        $t3, 0xDC($sp)
  .L80000C4C:
    /* 184C 80000C4C 3C068004 */  lui        $a2, %hi(D_800406A8)
    /* 1850 80000C50 8CC606A8 */  lw         $a2, %lo(D_800406A8)($a2)
    /* 1854 80000C54 8FAA00E0 */  lw         $t2, 0xE0($sp)
    /* 1858 80000C58 27A4007C */  addiu      $a0, $sp, 0x7C
    /* 185C 80000C5C 10C00009 */  beqz       $a2, .L80000C84
    /* 1860 80000C60 3C058004 */   lui       $a1, %hi(D_8003D200)
    /* 1864 80000C64 3C058004 */  lui        $a1, %hi(D_8003D1EC)
    /* 1868 80000C68 3C078004 */  lui        $a3, %hi(D_800406AC)
    /* 186C 80000C6C 8CE706AC */  lw         $a3, %lo(D_800406AC)($a3)
    /* 1870 80000C70 24A5D1EC */  addiu      $a1, $a1, %lo(D_8003D1EC)
    /* 1874 80000C74 0C00B631 */  jal        func_8002D8C4
    /* 1878 80000C78 27A4007C */   addiu     $a0, $sp, 0x7C
    /* 187C 80000C7C 10000009 */  b          .L80000CA4
    /* 1880 80000C80 8FAB00DC */   lw        $t3, 0xDC($sp)
  .L80000C84:
    /* 1884 80000C84 11400003 */  beqz       $t2, .L80000C94
    /* 1888 80000C88 3C068004 */   lui       $a2, %hi(D_8003D214)
    /* 188C 80000C8C 10000002 */  b          .L80000C98
    /* 1890 80000C90 01403025 */   or        $a2, $t2, $zero
  .L80000C94:
    /* 1894 80000C94 24C6D214 */  addiu      $a2, $a2, %lo(D_8003D214)
  .L80000C98:
    /* 1898 80000C98 0C00B631 */  jal        func_8002D8C4
    /* 189C 80000C9C 24A5D200 */   addiu     $a1, $a1, %lo(D_8003D200)
    /* 18A0 80000CA0 8FAB00DC */  lw         $t3, 0xDC($sp)
  .L80000CA4:
    /* 18A4 80000CA4 3C058004 */  lui        $a1, %hi(D_8003D218)
    /* 18A8 80000CA8 24A5D218 */  addiu      $a1, $a1, %lo(D_8003D218)
    /* 18AC 80000CAC 11600003 */  beqz       $t3, .L80000CBC
    /* 18B0 80000CB0 27A4002C */   addiu     $a0, $sp, 0x2C
    /* 18B4 80000CB4 10000004 */  b          .L80000CC8
    /* 18B8 80000CB8 AFAB0028 */   sw        $t3, 0x28($sp)
  .L80000CBC:
    /* 18BC 80000CBC 3C068004 */  lui        $a2, %hi(D_8003D22C)
    /* 18C0 80000CC0 24C6D22C */  addiu      $a2, $a2, %lo(D_8003D22C)
    /* 18C4 80000CC4 AFA60028 */  sw         $a2, 0x28($sp)
  .L80000CC8:
    /* 18C8 80000CC8 8FAC00CC */  lw         $t4, 0xCC($sp)
    /* 18CC 80000CCC 8FAD0028 */  lw         $t5, 0x28($sp)
    /* 18D0 80000CD0 8FA600D4 */  lw         $a2, 0xD4($sp)
    /* 18D4 80000CD4 8FA700D0 */  lw         $a3, 0xD0($sp)
    /* 18D8 80000CD8 AFAC0010 */  sw         $t4, 0x10($sp)
    /* 18DC 80000CDC 0C00B631 */  jal        func_8002D8C4
    /* 18E0 80000CE0 AFAD0014 */   sw        $t5, 0x14($sp)
    /* 18E4 80000CE4 27A4007C */  addiu      $a0, $sp, 0x7C
    /* 18E8 80000CE8 0C00A6AD */  jal        func_80029AB4
    /* 18EC 80000CEC 27A5002C */   addiu     $a1, $sp, 0x2C
    /* 18F0 80000CF0 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 18F4 80000CF4 27BD00D8 */  addiu      $sp, $sp, 0xD8
    /* 18F8 80000CF8 03E00008 */  jr         $ra
    /* 18FC 80000CFC 00000000 */   nop
endlabel func_80000BF0

nonmatching func_80000D00, 0x1C4

glabel func_80000D00
    /* 1900 80000D00 27BDFF68 */  addiu      $sp, $sp, -0x98
    /* 1904 80000D04 AFB40024 */  sw         $s4, 0x24($sp)
    /* 1908 80000D08 AFB2001C */  sw         $s2, 0x1C($sp)
    /* 190C 80000D0C AFB10018 */  sw         $s1, 0x18($sp)
    /* 1910 80000D10 00808825 */  or         $s1, $a0, $zero
    /* 1914 80000D14 00C09025 */  or         $s2, $a2, $zero
    /* 1918 80000D18 00A0A025 */  or         $s4, $a1, $zero
    /* 191C 80000D1C AFBF0034 */  sw         $ra, 0x34($sp)
    /* 1920 80000D20 AFB70030 */  sw         $s7, 0x30($sp)
    /* 1924 80000D24 AFB6002C */  sw         $s6, 0x2C($sp)
    /* 1928 80000D28 AFB50028 */  sw         $s5, 0x28($sp)
    /* 192C 80000D2C AFB30020 */  sw         $s3, 0x20($sp)
    /* 1930 80000D30 AFB00014 */  sw         $s0, 0x14($sp)
    /* 1934 80000D34 3C108004 */  lui        $s0, %hi(D_8003BBE0)
    /* 1938 80000D38 001177C0 */  sll        $t6, $s1, 31
    /* 193C 80000D3C 15C00005 */  bnez       $t6, .L80000D54
    /* 1940 80000D40 8E10BBE0 */   lw        $s0, %lo(D_8003BBE0)($s0)
    /* 1944 80000D44 00147F40 */  sll        $t7, $s4, 29
    /* 1948 80000D48 15E00002 */  bnez       $t7, .L80000D54
    /* 194C 80000D4C 0012C7C0 */   sll       $t8, $s2, 31
    /* 1950 80000D50 1300000E */  beqz       $t8, .L80000D8C
  .L80000D54:
    /* 1954 80000D54 3C198004 */   lui       $t9, %hi(D_8003D230)
    /* 1958 80000D58 2739D230 */  addiu      $t9, $t9, %lo(D_8003D230)
    /* 195C 80000D5C 3C068004 */  lui        $a2, %hi(D_8003D23C)
    /* 1960 80000D60 3C078004 */  lui        $a3, %hi(D_8003D250)
    /* 1964 80000D64 AFB1003C */  sw         $s1, 0x3C($sp)
    /* 1968 80000D68 AFB40040 */  sw         $s4, 0x40($sp)
    /* 196C 80000D6C AFB20044 */  sw         $s2, 0x44($sp)
    /* 1970 80000D70 AFB90048 */  sw         $t9, 0x48($sp)
    /* 1974 80000D74 AFA0004C */  sw         $zero, 0x4C($sp)
    /* 1978 80000D78 24E7D250 */  addiu      $a3, $a3, %lo(D_8003D250)
    /* 197C 80000D7C 24C6D23C */  addiu      $a2, $a2, %lo(D_8003D23C)
    /* 1980 80000D80 27A4003C */  addiu      $a0, $sp, 0x3C
    /* 1984 80000D84 0C0098FC */  jal        func_800263F0
    /* 1988 80000D88 00002825 */   or        $a1, $zero, $zero
  .L80000D8C:
    /* 198C 80000D8C 02802025 */  or         $a0, $s4, $zero
    /* 1990 80000D90 0C00D30C */  jal        func_80034C30
    /* 1994 80000D94 02402825 */   or        $a1, $s2, $zero
    /* 1998 80000D98 27B50068 */  addiu      $s5, $sp, 0x68
    /* 199C 80000D9C 02A02025 */  or         $a0, $s5, $zero
    /* 19A0 80000DA0 27A50064 */  addiu      $a1, $sp, 0x64
    /* 19A4 80000DA4 0C00D358 */  jal        func_80034D60
    /* 19A8 80000DA8 24060001 */   addiu     $a2, $zero, 0x1
    /* 19AC 80000DAC 1200001E */  beqz       $s0, .L80000E28
    /* 19B0 80000DB0 0212082B */   sltu      $at, $s0, $s2
    /* 19B4 80000DB4 1020001C */  beqz       $at, .L80000E28
    /* 19B8 80000DB8 27B70080 */   addiu     $s7, $sp, 0x80
    /* 19BC 80000DBC 3C168004 */  lui        $s6, %hi(D_8003BBD0)
    /* 19C0 80000DC0 3C138004 */  lui        $s3, %hi(D_800406B0)
    /* 19C4 80000DC4 267306B0 */  addiu      $s3, $s3, %lo(D_800406B0)
    /* 19C8 80000DC8 26D6BBD0 */  addiu      $s6, $s6, %lo(D_8003BBD0)
  .L80000DCC:
    /* 19CC 80000DCC 8E680000 */  lw         $t0, 0x0($s3)
    /* 19D0 80000DD0 A3A00082 */  sb         $zero, 0x82($sp)
    /* 19D4 80000DD4 AFB50084 */  sw         $s5, 0x84($sp)
    /* 19D8 80000DD8 01104821 */  addu       $t1, $t0, $s0
    /* 19DC 80000DDC AFB1008C */  sw         $s1, 0x8C($sp)
    /* 19E0 80000DE0 AFB40088 */  sw         $s4, 0x88($sp)
    /* 19E4 80000DE4 AFB00090 */  sw         $s0, 0x90($sp)
    /* 19E8 80000DE8 AE690000 */  sw         $t1, 0x0($s3)
    /* 19EC 80000DEC 8EC40000 */  lw         $a0, 0x0($s6)
    /* 19F0 80000DF0 02E02825 */  or         $a1, $s7, $zero
    /* 19F4 80000DF4 0C00D2BC */  jal        func_80034AF0
    /* 19F8 80000DF8 00003025 */   or        $a2, $zero, $zero
    /* 19FC 80000DFC 14400025 */  bnez       $v0, .L80000E94
    /* 1A00 80000E00 00401825 */   or        $v1, $v0, $zero
    /* 1A04 80000E04 02A02025 */  or         $a0, $s5, $zero
    /* 1A08 80000E08 00002825 */  or         $a1, $zero, $zero
    /* 1A0C 80000E0C 0C00B7E8 */  jal        func_8002DFA0
    /* 1A10 80000E10 24060001 */   addiu     $a2, $zero, 0x1
    /* 1A14 80000E14 02509023 */  subu       $s2, $s2, $s0
    /* 1A18 80000E18 0212082B */  sltu       $at, $s0, $s2
    /* 1A1C 80000E1C 02308821 */  addu       $s1, $s1, $s0
    /* 1A20 80000E20 1420FFEA */  bnez       $at, .L80000DCC
    /* 1A24 80000E24 0290A021 */   addu      $s4, $s4, $s0
  .L80000E28:
    /* 1A28 80000E28 3C138004 */  lui        $s3, %hi(D_800406B0)
    /* 1A2C 80000E2C 267306B0 */  addiu      $s3, $s3, %lo(D_800406B0)
    /* 1A30 80000E30 8E6A0000 */  lw         $t2, 0x0($s3)
    /* 1A34 80000E34 3C168004 */  lui        $s6, %hi(D_8003BBD0)
    /* 1A38 80000E38 26D6BBD0 */  addiu      $s6, $s6, %lo(D_8003BBD0)
    /* 1A3C 80000E3C 01525821 */  addu       $t3, $t2, $s2
    /* 1A40 80000E40 27A50080 */  addiu      $a1, $sp, 0x80
    /* 1A44 80000E44 A3A00082 */  sb         $zero, 0x82($sp)
    /* 1A48 80000E48 AFB50084 */  sw         $s5, 0x84($sp)
    /* 1A4C 80000E4C AFB1008C */  sw         $s1, 0x8C($sp)
    /* 1A50 80000E50 AFB40088 */  sw         $s4, 0x88($sp)
    /* 1A54 80000E54 AFB20090 */  sw         $s2, 0x90($sp)
    /* 1A58 80000E58 AE6B0000 */  sw         $t3, 0x0($s3)
    /* 1A5C 80000E5C 8EC40000 */  lw         $a0, 0x0($s6)
    /* 1A60 80000E60 0C00D2BC */  jal        func_80034AF0
    /* 1A64 80000E64 00003025 */   or        $a2, $zero, $zero
    /* 1A68 80000E68 1440000A */  bnez       $v0, .L80000E94
    /* 1A6C 80000E6C 00401825 */   or        $v1, $v0, $zero
    /* 1A70 80000E70 02A02025 */  or         $a0, $s5, $zero
    /* 1A74 80000E74 00002825 */  or         $a1, $zero, $zero
    /* 1A78 80000E78 24060001 */  addiu      $a2, $zero, 0x1
    /* 1A7C 80000E7C 0C00B7E8 */  jal        func_8002DFA0
    /* 1A80 80000E80 AFA20060 */   sw        $v0, 0x60($sp)
    /* 1A84 80000E84 02802025 */  or         $a0, $s4, $zero
    /* 1A88 80000E88 0C00D30C */  jal        func_80034C30
    /* 1A8C 80000E8C 02402825 */   or        $a1, $s2, $zero
    /* 1A90 80000E90 8FA30060 */  lw         $v1, 0x60($sp)
  .L80000E94:
    /* 1A94 80000E94 00601025 */  or         $v0, $v1, $zero
    /* 1A98 80000E98 8FBF0034 */  lw         $ra, 0x34($sp)
    /* 1A9C 80000E9C 8FB00014 */  lw         $s0, 0x14($sp)
    /* 1AA0 80000EA0 8FB10018 */  lw         $s1, 0x18($sp)
    /* 1AA4 80000EA4 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 1AA8 80000EA8 8FB30020 */  lw         $s3, 0x20($sp)
    /* 1AAC 80000EAC 8FB40024 */  lw         $s4, 0x24($sp)
    /* 1AB0 80000EB0 8FB50028 */  lw         $s5, 0x28($sp)
    /* 1AB4 80000EB4 8FB6002C */  lw         $s6, 0x2C($sp)
    /* 1AB8 80000EB8 8FB70030 */  lw         $s7, 0x30($sp)
    /* 1ABC 80000EBC 03E00008 */  jr         $ra
    /* 1AC0 80000EC0 27BD0098 */   addiu     $sp, $sp, 0x98
endlabel func_80000D00

nonmatching func_80000EC4, 0x50

glabel func_80000EC4
    /* 1AC4 80000EC4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1AC8 80000EC8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1ACC 80000ECC 0C00D2BC */  jal        func_80034AF0
    /* 1AD0 80000ED0 AFA5001C */   sw        $a1, 0x1C($sp)
    /* 1AD4 80000ED4 8FA5001C */  lw         $a1, 0x1C($sp)
    /* 1AD8 80000ED8 3C038004 */  lui        $v1, %hi(D_800406B0)
    /* 1ADC 80000EDC 246306B0 */  addiu      $v1, $v1, %lo(D_800406B0)
    /* 1AE0 80000EE0 8C6E0000 */  lw         $t6, 0x0($v1)
    /* 1AE4 80000EE4 8CAF0010 */  lw         $t7, 0x10($a1)
    /* 1AE8 80000EE8 3C048004 */  lui        $a0, %hi(D_800406B4)
    /* 1AEC 80000EEC 248406B4 */  addiu      $a0, $a0, %lo(D_800406B4)
    /* 1AF0 80000EF0 01CFC021 */  addu       $t8, $t6, $t7
    /* 1AF4 80000EF4 AC780000 */  sw         $t8, 0x0($v1)
    /* 1AF8 80000EF8 8C990000 */  lw         $t9, 0x0($a0)
    /* 1AFC 80000EFC 8CA80010 */  lw         $t0, 0x10($a1)
    /* 1B00 80000F00 03284821 */  addu       $t1, $t9, $t0
    /* 1B04 80000F04 AC890000 */  sw         $t1, 0x0($a0)
    /* 1B08 80000F08 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1B0C 80000F0C 03E00008 */  jr         $ra
    /* 1B10 80000F10 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_80000EC4

nonmatching func_80000F14, 0x5C

glabel func_80000F14
    /* 1B14 80000F14 3C028004 */  lui        $v0, %hi(D_80044690)
    /* 1B18 80000F18 24424690 */  addiu      $v0, $v0, %lo(D_80044690)
    /* 1B1C 80000F1C 8C4E0004 */  lw         $t6, 0x4($v0)
    /* 1B20 80000F20 00401825 */  or         $v1, $v0, $zero
    /* 1B24 80000F24 51C00010 */  beql       $t6, $zero, .L80000F68
    /* 1B28 80000F28 00001025 */   or        $v0, $zero, $zero
    /* 1B2C 80000F2C 8C6F0000 */  lw         $t7, 0x0($v1)
  .L80000F30:
    /* 1B30 80000F30 008F082B */  sltu       $at, $a0, $t7
    /* 1B34 80000F34 54200008 */  bnel       $at, $zero, .L80000F58
    /* 1B38 80000F38 8C790014 */   lw        $t9, 0x14($v1)
    /* 1B3C 80000F3C 8C780004 */  lw         $t8, 0x4($v1)
    /* 1B40 80000F40 0098082B */  sltu       $at, $a0, $t8
    /* 1B44 80000F44 50200004 */  beql       $at, $zero, .L80000F58
    /* 1B48 80000F48 8C790014 */   lw        $t9, 0x14($v1)
    /* 1B4C 80000F4C 03E00008 */  jr         $ra
    /* 1B50 80000F50 00601025 */   or        $v0, $v1, $zero
    /* 1B54 80000F54 8C790014 */  lw         $t9, 0x14($v1)
  .L80000F58:
    /* 1B58 80000F58 24630010 */  addiu      $v1, $v1, 0x10
    /* 1B5C 80000F5C 5720FFF4 */  bnel       $t9, $zero, .L80000F30
    /* 1B60 80000F60 8C6F0000 */   lw        $t7, 0x0($v1)
    /* 1B64 80000F64 00001025 */  or         $v0, $zero, $zero
  .L80000F68:
    /* 1B68 80000F68 03E00008 */  jr         $ra
    /* 1B6C 80000F6C 00000000 */   nop
endlabel func_80000F14

nonmatching func_80000F70, 0x6C

glabel func_80000F70
    /* 1B70 80000F70 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1B74 80000F74 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1B78 80000F78 0C0099C5 */  jal        func_80026714
    /* 1B7C 80000F7C AFA40018 */   sw        $a0, 0x18($sp)
    /* 1B80 80000F80 8FA40018 */  lw         $a0, 0x18($sp)
    /* 1B84 80000F84 10400010 */  beqz       $v0, .L80000FC8
    /* 1B88 80000F88 00401825 */   or        $v1, $v0, $zero
    /* 1B8C 80000F8C 8C4E000C */  lw         $t6, 0xC($v0)
    /* 1B90 80000F90 55C00007 */  bnel       $t6, $zero, .L80000FB0
    /* 1B94 80000F94 8C480000 */   lw        $t0, 0x0($v0)
    /* 1B98 80000F98 8C6F0008 */  lw         $t7, 0x8($v1)
    /* 1B9C 80000F9C 8C790000 */  lw         $t9, 0x0($v1)
    /* 1BA0 80000FA0 01E4C021 */  addu       $t8, $t7, $a0
    /* 1BA4 80000FA4 10000009 */  b          .L80000FCC
    /* 1BA8 80000FA8 03191023 */   subu      $v0, $t8, $t9
    /* 1BAC 80000FAC 8C480000 */  lw         $t0, 0x0($v0)
  .L80000FB0:
    /* 1BB0 80000FB0 14880003 */  bne        $a0, $t0, .L80000FC0
    /* 1BB4 80000FB4 00000000 */   nop
    /* 1BB8 80000FB8 10000004 */  b          .L80000FCC
    /* 1BBC 80000FBC 8C620008 */   lw        $v0, 0x8($v1)
  .L80000FC0:
    /* 1BC0 80000FC0 10000002 */  b          .L80000FCC
    /* 1BC4 80000FC4 2402FFFF */   addiu     $v0, $zero, -0x1
  .L80000FC8:
    /* 1BC8 80000FC8 2402FFFF */  addiu      $v0, $zero, -0x1
  .L80000FCC:
    /* 1BCC 80000FCC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1BD0 80000FD0 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 1BD4 80000FD4 03E00008 */  jr         $ra
    /* 1BD8 80000FD8 00000000 */   nop
endlabel func_80000F70

nonmatching func_80000FDC, 0x38

glabel func_80000FDC
    /* 1BDC 80000FDC 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1BE0 80000FE0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1BE4 80000FE4 0C0099C5 */  jal        func_80026714
    /* 1BE8 80000FE8 00000000 */   nop
    /* 1BEC 80000FEC 10400006 */  beqz       $v0, .L80001008
    /* 1BF0 80000FF0 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 1BF4 80000FF4 3C0E8004 */  lui        $t6, %hi(D_80044690)
    /* 1BF8 80000FF8 25CE4690 */  addiu      $t6, $t6, %lo(D_80044690)
    /* 1BFC 80000FFC 004E1023 */  subu       $v0, $v0, $t6
    /* 1C00 80001000 10000002 */  b          .L8000100C
    /* 1C04 80001004 00021103 */   sra       $v0, $v0, 4
  .L80001008:
    /* 1C08 80001008 2402FFFF */  addiu      $v0, $zero, -0x1
  .L8000100C:
    /* 1C0C 8000100C 03E00008 */  jr         $ra
    /* 1C10 80001010 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_80000FDC

nonmatching func_80001014, 0x14

glabel func_80001014
    /* 1C14 80001014 AFA40000 */  sw         $a0, 0x0($sp)
    /* 1C18 80001018 3C028004 */  lui        $v0, %hi(D_8003D264)
    /* 1C1C 8000101C 2442D264 */  addiu      $v0, $v0, %lo(D_8003D264)
    /* 1C20 80001020 03E00008 */  jr         $ra
    /* 1C24 80001024 00000000 */   nop
endlabel func_80001014

nonmatching func_80001028, 0x1BC

glabel func_80001028
    /* 1C28 80001028 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 1C2C 8000102C AFB00018 */  sw         $s0, 0x18($sp)
    /* 1C30 80001030 00808025 */  or         $s0, $a0, $zero
    /* 1C34 80001034 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 1C38 80001038 8E0E0004 */  lw         $t6, 0x4($s0)
    /* 1C3C 8000103C 8E040000 */  lw         $a0, 0x0($s0)
    /* 1C40 80001040 AFAE0038 */  sw         $t6, 0x38($sp)
    /* 1C44 80001044 8E0F0008 */  lw         $t7, 0x8($s0)
    /* 1C48 80001048 AFA4003C */  sw         $a0, 0x3C($sp)
    /* 1C4C 8000104C 0C0099F7 */  jal        func_800267DC
    /* 1C50 80001050 AFAF0034 */   sw        $t7, 0x34($sp)
    /* 1C54 80001054 8FA9003C */  lw         $t1, 0x3C($sp)
    /* 1C58 80001058 04400056 */  bltz       $v0, .L800011B4
    /* 1C5C 8000105C 00404025 */   or        $t0, $v0, $zero
    /* 1C60 80001060 3C188004 */  lui        $t8, %hi(D_8003FF5C)
    /* 1C64 80001064 9718FF5C */  lhu        $t8, %lo(D_8003FF5C)($t8)
    /* 1C68 80001068 3C0A8004 */  lui        $t2, %hi(D_80044690)
    /* 1C6C 8000106C 254A4690 */  addiu      $t2, $t2, %lo(D_80044690)
    /* 1C70 80001070 0058082A */  slt        $at, $v0, $t8
    /* 1C74 80001074 1020004F */  beqz       $at, .L800011B4
    /* 1C78 80001078 0002C900 */   sll       $t9, $v0, 4
    /* 1C7C 8000107C 032A2021 */  addu       $a0, $t9, $t2
    /* 1C80 80001080 8C85000C */  lw         $a1, 0xC($a0)
    /* 1C84 80001084 8FAC0034 */  lw         $t4, 0x34($sp)
    /* 1C88 80001088 54A0001E */  bnel       $a1, $zero, .L80001104
    /* 1C8C 8000108C 8C830008 */   lw        $v1, 0x8($a0)
    /* 1C90 80001090 8C8B0004 */  lw         $t3, 0x4($a0)
    /* 1C94 80001094 012C6821 */  addu       $t5, $t1, $t4
    /* 1C98 80001098 02002025 */  or         $a0, $s0, $zero
    /* 1C9C 8000109C 016D082B */  sltu       $at, $t3, $t5
    /* 1CA0 800010A0 1020000A */  beqz       $at, .L800010CC
    /* 1CA4 800010A4 3C058004 */   lui       $a1, %hi(D_8003D268)
    /* 1CA8 800010A8 3C068004 */  lui        $a2, %hi(D_8003D26C)
    /* 1CAC 800010AC 3C078004 */  lui        $a3, %hi(D_8003D284)
    /* 1CB0 800010B0 24E7D284 */  addiu      $a3, $a3, %lo(D_8003D284)
    /* 1CB4 800010B4 24C6D26C */  addiu      $a2, $a2, %lo(D_8003D26C)
    /* 1CB8 800010B8 24A5D268 */  addiu      $a1, $a1, %lo(D_8003D268)
    /* 1CBC 800010BC 0C0098FC */  jal        func_800263F0
    /* 1CC0 800010C0 AFA20024 */   sw        $v0, 0x24($sp)
    /* 1CC4 800010C4 8FA80024 */  lw         $t0, 0x24($sp)
    /* 1CC8 800010C8 8FA9003C */  lw         $t1, 0x3C($sp)
  .L800010CC:
    /* 1CCC 800010CC 3C0F8004 */  lui        $t7, %hi(D_80044690)
    /* 1CD0 800010D0 25EF4690 */  addiu      $t7, $t7, %lo(D_80044690)
    /* 1CD4 800010D4 00087100 */  sll        $t6, $t0, 4
    /* 1CD8 800010D8 01CF1021 */  addu       $v0, $t6, $t7
    /* 1CDC 800010DC 8C580008 */  lw         $t8, 0x8($v0)
    /* 1CE0 800010E0 8C4A0000 */  lw         $t2, 0x0($v0)
    /* 1CE4 800010E4 8FA50038 */  lw         $a1, 0x38($sp)
    /* 1CE8 800010E8 0309C821 */  addu       $t9, $t8, $t1
    /* 1CEC 800010EC 8FA60034 */  lw         $a2, 0x34($sp)
    /* 1CF0 800010F0 0C009940 */  jal        func_80026500
    /* 1CF4 800010F4 032A2023 */   subu      $a0, $t9, $t2
    /* 1CF8 800010F8 10000036 */  b          .L800011D4
    /* 1CFC 800010FC 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 1D00 80001100 8C830008 */  lw         $v1, 0x8($a0)
  .L80001104:
    /* 1D04 80001104 3C068004 */  lui        $a2, %hi(D_8003D2C4)
    /* 1D08 80001108 24C6D2C4 */  addiu      $a2, $a2, %lo(D_8003D2C4)
    /* 1D0C 8000110C 00A36023 */  subu       $t4, $a1, $v1
    /* 1D10 80001110 AFAC002C */  sw         $t4, 0x2C($sp)
    /* 1D14 80001114 AFA30030 */  sw         $v1, 0x30($sp)
    /* 1D18 80001118 8C8B0000 */  lw         $t3, 0x0($a0)
    /* 1D1C 8000111C 3C058004 */  lui        $a1, %hi(D_8003D2C0)
    /* 1D20 80001120 24A5D2C0 */  addiu      $a1, $a1, %lo(D_8003D2C0)
    /* 1D24 80001124 112B0006 */  beq        $t1, $t3, .L80001140
    /* 1D28 80001128 02002025 */   or        $a0, $s0, $zero
    /* 1D2C 8000112C 3C078004 */  lui        $a3, %hi(D_8003D2DC)
    /* 1D30 80001130 24E7D2DC */  addiu      $a3, $a3, %lo(D_8003D2DC)
    /* 1D34 80001134 0C0098FC */  jal        func_800263F0
    /* 1D38 80001138 AFA80024 */   sw        $t0, 0x24($sp)
    /* 1D3C 8000113C 8FA80024 */  lw         $t0, 0x24($sp)
  .L80001140:
    /* 1D40 80001140 3C0E8004 */  lui        $t6, %hi(D_80044690)
    /* 1D44 80001144 25CE4690 */  addiu      $t6, $t6, %lo(D_80044690)
    /* 1D48 80001148 00086900 */  sll        $t5, $t0, 4
    /* 1D4C 8000114C 01AE1021 */  addu       $v0, $t5, $t6
    /* 1D50 80001150 8C580004 */  lw         $t8, 0x4($v0)
    /* 1D54 80001154 8C590000 */  lw         $t9, 0x0($v0)
    /* 1D58 80001158 8FAF0034 */  lw         $t7, 0x34($sp)
    /* 1D5C 8000115C 02002025 */  or         $a0, $s0, $zero
    /* 1D60 80001160 03195023 */  subu       $t2, $t8, $t9
    /* 1D64 80001164 11EA0007 */  beq        $t7, $t2, .L80001184
    /* 1D68 80001168 3C058004 */   lui       $a1, %hi(D_8003D31C)
    /* 1D6C 8000116C 3C068004 */  lui        $a2, %hi(D_8003D320)
    /* 1D70 80001170 3C078004 */  lui        $a3, %hi(D_8003D338)
    /* 1D74 80001174 24E7D338 */  addiu      $a3, $a3, %lo(D_8003D338)
    /* 1D78 80001178 24C6D320 */  addiu      $a2, $a2, %lo(D_8003D320)
    /* 1D7C 8000117C 0C0098FC */  jal        func_800263F0
    /* 1D80 80001180 24A5D31C */   addiu     $a1, $a1, %lo(D_8003D31C)
  .L80001184:
    /* 1D84 80001184 00002025 */  or         $a0, $zero, $zero
    /* 1D88 80001188 0C00D508 */  jal        func_80035420
    /* 1D8C 8000118C 2405000A */   addiu     $a1, $zero, 0xA
    /* 1D90 80001190 8FA40030 */  lw         $a0, 0x30($sp)
    /* 1D94 80001194 8FA50038 */  lw         $a1, 0x38($sp)
    /* 1D98 80001198 0C009C7A */  jal        func_800271E8
    /* 1D9C 8000119C 8FA6002C */   lw        $a2, 0x2C($sp)
    /* 1DA0 800011A0 00002025 */  or         $a0, $zero, $zero
    /* 1DA4 800011A4 0C00D508 */  jal        func_80035420
    /* 1DA8 800011A8 24050011 */   addiu     $a1, $zero, 0x11
    /* 1DAC 800011AC 10000009 */  b          .L800011D4
    /* 1DB0 800011B0 8FBF001C */   lw        $ra, 0x1C($sp)
  .L800011B4:
    /* 1DB4 800011B4 3C068004 */  lui        $a2, %hi(D_8003D378)
    /* 1DB8 800011B8 3C078004 */  lui        $a3, %hi(D_8003D38C)
    /* 1DBC 800011BC 24E7D38C */  addiu      $a3, $a3, %lo(D_8003D38C)
    /* 1DC0 800011C0 24C6D378 */  addiu      $a2, $a2, %lo(D_8003D378)
    /* 1DC4 800011C4 02002025 */  or         $a0, $s0, $zero
    /* 1DC8 800011C8 0C0098FC */  jal        func_800263F0
    /* 1DCC 800011CC 00002825 */   or        $a1, $zero, $zero
    /* 1DD0 800011D0 8FBF001C */  lw         $ra, 0x1C($sp)
  .L800011D4:
    /* 1DD4 800011D4 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1DD8 800011D8 27BD0040 */  addiu      $sp, $sp, 0x40
    /* 1DDC 800011DC 03E00008 */  jr         $ra
    /* 1DE0 800011E0 00000000 */   nop
endlabel func_80001028

nonmatching func_800011E4, 0x80

glabel func_800011E4
    /* 1DE4 800011E4 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 1DE8 800011E8 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 1DEC 800011EC AFB20020 */  sw         $s2, 0x20($sp)
    /* 1DF0 800011F0 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 1DF4 800011F4 AFB00018 */  sw         $s0, 0x18($sp)
    /* 1DF8 800011F8 AFA40038 */  sw         $a0, 0x38($sp)
    /* 1DFC 800011FC 3C118004 */  lui        $s1, %hi(D_8003FF60)
    /* 1E00 80001200 2631FF60 */  addiu      $s1, $s1, %lo(D_8003FF60)
    /* 1E04 80001204 27B20034 */  addiu      $s2, $sp, 0x34
    /* 1E08 80001208 02202025 */  or         $a0, $s1, $zero
  .L8000120C:
    /* 1E0C 8000120C 02402825 */  or         $a1, $s2, $zero
    /* 1E10 80001210 0C00B7E8 */  jal        func_8002DFA0
    /* 1E14 80001214 24060001 */   addiu     $a2, $zero, 0x1
    /* 1E18 80001218 8FA40034 */  lw         $a0, 0x34($sp)
    /* 1E1C 8000121C 5080000C */  beql       $a0, $zero, .L80001250
    /* 1E20 80001220 8FBF0024 */   lw        $ra, 0x24($sp)
    /* 1E24 80001224 0C009A0A */  jal        func_80026828
    /* 1E28 80001228 00808025 */   or        $s0, $a0, $zero
    /* 1E2C 8000122C 8E040018 */  lw         $a0, 0x18($s0)
    /* 1E30 80001230 5080FFF6 */  beql       $a0, $zero, .L8000120C
    /* 1E34 80001234 02202025 */   or        $a0, $s1, $zero
    /* 1E38 80001238 8E05001C */  lw         $a1, 0x1C($s0)
    /* 1E3C 8000123C 0C00B6C8 */  jal        func_8002DB20
    /* 1E40 80001240 00003025 */   or        $a2, $zero, $zero
    /* 1E44 80001244 1000FFF1 */  b          .L8000120C
    /* 1E48 80001248 02202025 */   or        $a0, $s1, $zero
    /* 1E4C 8000124C 8FBF0024 */  lw         $ra, 0x24($sp)
  .L80001250:
    /* 1E50 80001250 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1E54 80001254 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 1E58 80001258 8FB20020 */  lw         $s2, 0x20($sp)
    /* 1E5C 8000125C 03E00008 */  jr         $ra
    /* 1E60 80001260 27BD0038 */   addiu     $sp, $sp, 0x38
endlabel func_800011E4

nonmatching func_80001264, 0xE0

glabel func_80001264
    /* 1E64 80001264 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 1E68 80001268 AFB00018 */  sw         $s0, 0x18($sp)
    /* 1E6C 8000126C 00808025 */  or         $s0, $a0, $zero
    /* 1E70 80001270 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 1E74 80001274 3C0E8011 */  lui        $t6, %hi(D_8010EFB0)
    /* 1E78 80001278 25CEEFB0 */  addiu      $t6, $t6, %lo(D_8010EFB0)
    /* 1E7C 8000127C 8DCF0000 */  lw         $t7, 0x0($t6)
    /* 1E80 80001280 29E10002 */  slti       $at, $t7, 0x2
    /* 1E84 80001284 54200004 */  bnel       $at, $zero, .L80001298
    /* 1E88 80001288 AE060000 */   sw        $a2, 0x0($s0)
    /* 1E8C 8000128C 10000028 */  b          .L80001330
    /* 1E90 80001290 2402FFFE */   addiu     $v0, $zero, -0x2
    /* 1E94 80001294 AE060000 */  sw         $a2, 0x0($s0)
  .L80001298:
    /* 1E98 80001298 AE050004 */  sw         $a1, 0x4($s0)
    /* 1E9C 8000129C AE070008 */  sw         $a3, 0x8($s0)
    /* 1EA0 800012A0 AE000014 */  sw         $zero, 0x14($s0)
    /* 1EA4 800012A4 8FB80034 */  lw         $t8, 0x34($sp)
    /* 1EA8 800012A8 3C088000 */  lui        $t0, %hi(D_80000318)
    /* 1EAC 800012AC 00A74821 */  addu       $t1, $a1, $a3
    /* 1EB0 800012B0 AE180018 */  sw         $t8, 0x18($s0)
    /* 1EB4 800012B4 8FB90038 */  lw         $t9, 0x38($sp)
    /* 1EB8 800012B8 02002025 */  or         $a0, $s0, $zero
    /* 1EBC 800012BC 10A00010 */  beqz       $a1, .L80001300
    /* 1EC0 800012C0 AE19001C */   sw        $t9, 0x1C($s0)
    /* 1EC4 800012C4 8D080318 */  lw         $t0, %lo(D_80000318)($t0)
    /* 1EC8 800012C8 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 1ECC 800012CC 01215021 */  addu       $t2, $t1, $at
    /* 1ED0 800012D0 010A082B */  sltu       $at, $t0, $t2
    /* 1ED4 800012D4 1420000A */  bnez       $at, .L80001300
    /* 1ED8 800012D8 30CB0001 */   andi      $t3, $a2, 0x1
    /* 1EDC 800012DC 15600008 */  bnez       $t3, .L80001300
    /* 1EE0 800012E0 3C010400 */   lui       $at, (0x4000001 >> 16)
    /* 1EE4 800012E4 34210001 */  ori        $at, $at, (0x4000001 & 0xFFFF)
    /* 1EE8 800012E8 00C1082B */  sltu       $at, $a2, $at
    /* 1EEC 800012EC 10200004 */  beqz       $at, .L80001300
    /* 1EF0 800012F0 00000000 */   nop
    /* 1EF4 800012F4 10E00002 */  beqz       $a3, .L80001300
    /* 1EF8 800012F8 30EC0001 */   andi      $t4, $a3, 0x1
    /* 1EFC 800012FC 11800006 */  beqz       $t4, .L80001318
  .L80001300:
    /* 1F00 80001300 3C068004 */   lui       $a2, %hi(D_8003D3AC)
    /* 1F04 80001304 3C078004 */  lui        $a3, %hi(D_8003D3C8)
    /* 1F08 80001308 24E7D3C8 */  addiu      $a3, $a3, %lo(D_8003D3C8)
    /* 1F0C 8000130C 24C6D3AC */  addiu      $a2, $a2, %lo(D_8003D3AC)
    /* 1F10 80001310 0C0098FC */  jal        func_800263F0
    /* 1F14 80001314 00002825 */   or        $a1, $zero, $zero
  .L80001318:
    /* 1F18 80001318 3C048004 */  lui        $a0, %hi(D_8003FF60)
    /* 1F1C 8000131C 2484FF60 */  addiu      $a0, $a0, %lo(D_8003FF60)
    /* 1F20 80001320 02002825 */  or         $a1, $s0, $zero
    /* 1F24 80001324 0C00B6C8 */  jal        func_8002DB20
    /* 1F28 80001328 24060001 */   addiu     $a2, $zero, 0x1
    /* 1F2C 8000132C 00001025 */  or         $v0, $zero, $zero
  .L80001330:
    /* 1F30 80001330 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 1F34 80001334 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1F38 80001338 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 1F3C 8000133C 03E00008 */  jr         $ra
    /* 1F40 80001340 00000000 */   nop
endlabel func_80001264

nonmatching func_80001344, 0x7C

glabel func_80001344
    /* 1F44 80001344 27BDFF98 */  addiu      $sp, $sp, -0x68
    /* 1F48 80001348 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 1F4C 8000134C AFA40068 */  sw         $a0, 0x68($sp)
    /* 1F50 80001350 AFA5006C */  sw         $a1, 0x6C($sp)
    /* 1F54 80001354 AFA60070 */  sw         $a2, 0x70($sp)
    /* 1F58 80001358 27A40030 */  addiu      $a0, $sp, 0x30
    /* 1F5C 8000135C 27A5002C */  addiu      $a1, $sp, 0x2C
    /* 1F60 80001360 0C00D358 */  jal        func_80034D60
    /* 1F64 80001364 24060001 */   addiu     $a2, $zero, 0x1
    /* 1F68 80001368 27AE0030 */  addiu      $t6, $sp, 0x30
    /* 1F6C 8000136C AFAE0014 */  sw         $t6, 0x14($sp)
    /* 1F70 80001370 27A40048 */  addiu      $a0, $sp, 0x48
    /* 1F74 80001374 8FA50068 */  lw         $a1, 0x68($sp)
    /* 1F78 80001378 8FA6006C */  lw         $a2, 0x6C($sp)
    /* 1F7C 8000137C 8FA70070 */  lw         $a3, 0x70($sp)
    /* 1F80 80001380 AFA00010 */  sw         $zero, 0x10($sp)
    /* 1F84 80001384 0C009A99 */  jal        func_80026A64
    /* 1F88 80001388 AFA00018 */   sw        $zero, 0x18($sp)
    /* 1F8C 8000138C 2401FFFF */  addiu      $at, $zero, -0x1
    /* 1F90 80001390 14410003 */  bne        $v0, $at, .L800013A0
    /* 1F94 80001394 27A40030 */   addiu     $a0, $sp, 0x30
    /* 1F98 80001398 10000006 */  b          .L800013B4
    /* 1F9C 8000139C 8FBF0024 */   lw        $ra, 0x24($sp)
  .L800013A0:
    /* 1FA0 800013A0 00002825 */  or         $a1, $zero, $zero
    /* 1FA4 800013A4 0C00B7E8 */  jal        func_8002DFA0
    /* 1FA8 800013A8 24060001 */   addiu     $a2, $zero, 0x1
    /* 1FAC 800013AC 00001025 */  or         $v0, $zero, $zero
    /* 1FB0 800013B0 8FBF0024 */  lw         $ra, 0x24($sp)
  .L800013B4:
    /* 1FB4 800013B4 27BD0068 */  addiu      $sp, $sp, 0x68
    /* 1FB8 800013B8 03E00008 */  jr         $ra
    /* 1FBC 800013BC 00000000 */   nop
endlabel func_80001344

nonmatching func_800013C0, 0x40

glabel func_800013C0
    /* 1FC0 800013C0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1FC4 800013C4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1FC8 800013C8 AFA40018 */  sw         $a0, 0x18($sp)
    /* 1FCC 800013CC AFA5001C */  sw         $a1, 0x1C($sp)
    /* 1FD0 800013D0 0C0099C5 */  jal        func_80026714
    /* 1FD4 800013D4 8FA4001C */   lw        $a0, 0x1C($sp)
    /* 1FD8 800013D8 8C4E0004 */  lw         $t6, 0x4($v0)
    /* 1FDC 800013DC 8C4F0000 */  lw         $t7, 0x0($v0)
    /* 1FE0 800013E0 8FA40018 */  lw         $a0, 0x18($sp)
    /* 1FE4 800013E4 8FA5001C */  lw         $a1, 0x1C($sp)
    /* 1FE8 800013E8 0C009AD1 */  jal        func_80026B44
    /* 1FEC 800013EC 01CF3023 */   subu      $a2, $t6, $t7
    /* 1FF0 800013F0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1FF4 800013F4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 1FF8 800013F8 03E00008 */  jr         $ra
    /* 1FFC 800013FC 00000000 */   nop
endlabel func_800013C0
